import { Vehicle, Trend } from './types';

export const VEHICLES: Vehicle[] = [
  {
    id: '1',
    name: 'AVIO',
    model: 'NEON GT',
    price: '$89,000',
    range: '520 km',
    acceleration: '2.4s',
    topSpeed: '280 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478798/c_01_yphnqh.webp',
    category: 'Sport',
  },
  {
    id: '2',
    name: 'AVIO',
    model: 'ZENITH S',
    price: '$65,000',
    range: '610 km',
    acceleration: '3.8s',
    topSpeed: '240 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478799/c_02_rsutqr.webp',
    category: 'Sedan',
  },
  {
    id: '3',
    name: 'AVIO',
    model: 'ORION X',
    price: '$78,000',
    range: '480 km',
    acceleration: '4.2s',
    topSpeed: '220 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478798/c_03_xoptwx.webp',
    category: 'SUV',
  },
  {
    id: '4',
    name: 'AVIO',
    model: 'PULSAR R',
    price: '$112,000',
    range: '450 km',
    acceleration: '1.9s',
    topSpeed: '320 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478798/c_04_eglk00.webp',
    category: 'Hypercar',
  },
  {
    id: '5',
    name: 'AVIO',
    model: 'LUMINA E',
    price: '$52,000',
    range: '580 km',
    acceleration: '5.1s',
    topSpeed: '200 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478798/c_05_d9vuxo.webp',
    category: 'Compact',
  },
  {
    id: '6',
    name: 'AVIO',
    model: 'TITAN V',
    price: '$95,000',
    range: '700 km',
    acceleration: '4.5s',
    topSpeed: '190 km/h',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774478799/c_06_xrgenh.webp',
    category: 'Off-road',
  },
];

export const TRENDS: Trend[] = [
  {
    id: '1',
    title: 'Baterías de Estado Sólido',
    description: 'La próxima revolución en densidad energética y velocidades de carga ultra-rápidas.',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774485667/baterias_bxtlbf.webp',
    date: 'MAR 2026',
  },
  {
    id: '2',
    title: 'Visión Autónoma 4.0',
    description: 'AVIO Vision 2.0 lleva la autonomía de nivel 4 a la producción en serie.',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774485667/Visi%C3%B3n_dut4dm.webp',
    date: 'FEB 2026',
  },
  {
    id: '3',
    title: 'Aerodinámica del Silencio',
    description: 'Reducción de resistencia al viento mediante superficies activas inteligentes.',
    image: 'https://res.cloudinary.com/dk1tkgjpj/image/upload/v1774485666/Aerodin%C3%A1mica_d1d65q.webp',
    date: 'ENE 2026',
  },
];
